<a href="https://colab.research.google.com/github/Balla01/assignments-HW-Saver-LLP/blob/main/IN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/Example_Technical_Skills.csv")
af = pd.read_csv("/content/Raw_Skills_Dataset.csv")

In [4]:
af

                                            RAW DATA
0                                           What ifs
1                                          seniority
2                                        familiarity
3                                    functionalities
4                                            Lambdas
...                                              ...
34111                                    negotiation
34112                                      deadlines
34113  Self-motivated, enthusiastic and strong drive
34114                                    negotiation
34115                                      deadlines

[34116 rows x 1 columns]

In [5]:
df

                         Technology Skills
0                      SAP Fiori Developer
1    Oracle Instance Management & Strategy
2             Boomi Master Data Management
3    Digital Manufacturing on Cloud ( DMC)
4                                   DevOps
..                                     ...
974        Oracle Cloud Revenue Management
975       Oracle EBS Grid Contral Mgt Pack
976         Amazon Elastic MapReduce (EMR)
977                            Apache Kudu
978                             Oracle ESB

[979 rows x 1 columns]

In [6]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [7]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [8]:
def rem_punc(text):
  new_text="".join([c for c in text if c not in string.punctuation])
  return new_text
df['clean_data']=df['Technology Skills'].apply(lambda x: rem_punc(x))

In [9]:
df['lower_text']=df['clean_data'].apply(lambda x:x.lower())

In [10]:
df['tokenize'] = df.apply(lambda row: nltk.word_tokenize(row['lower_text']),axis=1)

In [11]:
stopwords=nltk.corpus.stopwords.words('english')

In [12]:
def remove_stopwords(txt):
  text=[word for word in txt if word not in stopwords]
  return text
df['stop_free']=df['tokenize'].apply(lambda x: remove_stopwords(x))

In [13]:
df

,Technology Skills,clean_data,lower_text,tokenize,stop_free
0,SAP Fiori Developer,SAP Fiori Developer,sap fiori developer,"[sap, fiori, developer]","[sap, fiori, developer]"
1,Oracle Instance Management & Strategy,Oracle Instance Management Strategy,oracle instance management strategy,"[oracle, instance, management, strategy]","[oracle, instance, management, strategy]"
2,Boomi Master Data Management,Boomi Master Data Management,boomi master data management,"[boomi, master, data, management]","[boomi, master, data, management]"
3,Digital Manufacturing on Cloud ( DMC),Digital Manufacturing on Cloud DMC,digital manufacturing on cloud dmc,"[digital, manufacturing, on, cloud, dmc]","[digital, manufacturing, cloud, dmc]"
4,DevOps,DevOps,devops,[devops],[devops]
...,...,...,...,...,...
974,Oracle Cloud Revenue Management,Oracle Cloud Revenue Management,oracle cloud revenue management,"[oracle, cloud, revenue, management]","[oracle, cloud, revenue, management]"
975,Oracle EBS Grid Contral Mgt Pack,Oracle EBS Grid Contral Mgt Pack,oracle ebs grid contral mgt pack,"[oracle, ebs, grid, contral, mgt, pack]","[oracle, ebs, grid, contral, mgt, pack]"
976,Amazon Elastic MapReduce (EMR),Amazon Elastic MapReduce EMR,amazon elastic mapreduce emr,"[amazon, elastic, mapreduce, emr]","[amazon, elastic, mapreduce, emr]"
977,Apache Kudu,Apache Kudu,apache kudu,"[apache, kudu]","[apache, kudu]"
978,Oracle ESB,Oracle ESB,oracle esb,"[oracle, esb]","[oracle, esb]"

In [14]:
def rem_punc(text):
  new_text="".join([c for c in text if c not in string.punctuation])
  return new_text
af['clean_data']=af['RAW DATA'].apply(lambda x: rem_punc(x))

In [15]:
af['lower_text1']=af['clean_data'].apply(lambda x:x.lower())

In [16]:
af['tokenize1'] = af.apply(lambda row: nltk.word_tokenize(row['lower_text1']),axis=1)

In [17]:
def remove_stopwords(txt):
  text=[word for word in txt if word not in stopwords]
  return text
af['stop_free1']=af['tokenize1'].apply(lambda x: remove_stopwords(x))

In [18]:
af

,RAW DATA,clean_data,lower_text1,tokenize1,stop_free1
0,What ifs,What ifs,what ifs,"[what, ifs]",[ifs]
1,seniority,seniority,seniority,[seniority],[seniority]
2,familiarity,familiarity,familiarity,[familiarity],[familiarity]
3,functionalities,functionalities,functionalities,[functionalities],[functionalities]
4,Lambdas,Lambdas,lambdas,[lambdas],[lambdas]
...,...,...,...,...,...
34111,negotiation,negotiation,negotiation,[negotiation],[negotiation]
34112,deadlines,deadlines,deadlines,[deadlines],[deadlines]
34113,"Self-motivated, enthusiastic and strong drive",Selfmotivated enthusiastic and strong drive,selfmotivated enthusiastic and strong drive,"[selfmotivated, enthusiastic, and, strong, drive]","[selfmotivated, enthusiastic, strong, drive]"
34114,negotiation,negotiation,negotiation,[negotiation],[negotiation]
34115,deadlines,deadlines,deadlines,[deadlines],[deadlines]

In [19]:
skills=['python']
for i in range(979):
  skills.extend(df['stop_free'][i])

In [20]:
skills

['python',
 'sap',
 'fiori',
 'developer',
 'oracle',
 'instance',
 'management',
 'strategy',
 'boomi',
 'master',
 'data',
 'management',
 'digital',
 'manufacturing',
 'cloud',
 'dmc',
 'devops',
 'ca',
 'sam',
 'openshift',
 'acxiom',
 'data',
 'analytics',
 'sap',
 'digital',
 'boardroom',
 'seeburger',
 'bis',
 'sap',
 'transport',
 'management',
 'peoplesoft',
 'workflow',
 'nice',
 'actimize',
 'oracle',
 'access',
 'manager',
 'sap',
 'electronic',
 'data',
 'interchange',
 'edi',
 'ideas',
 'crowdsourcing',
 'peoplesoft',
 'workforce',
 'planning',
 'sap',
 'benefits',
 'onesource',
 'rd',
 'credit',
 'manager',
 'sap',
 'consignment',
 'ms',
 'bot',
 'framework',
 'ibm',
 'websphere',
 'application',
 'server',
 'microsoft',
 'azure',
 'ad',
 'domain',
 'services',
 'sap',
 'ibp',
 'bpc',
 'oracle',
 'hyperion',
 'capital',
 'asset',
 'planning',
 'sap',
 'introscope',
 'wily',
 'ejb',
 'rmi',
 'sas',
 'base',
 'siebel',
 'modules',
 'non',
 'functional',
 'testing',
 'oracle',
 'cloud',
 'product',
 'hub',
 'data',
 'steward',
 'kronos',
 'wfc',
 'accruals',
 'configuration',
 'jde',
 'fixed',
 'assets',
 'sap',
 'tmewm',
 'integration',
 'peoplesoft',
 'payables',
 'netsuite',
 'case',
 'management',
 'mysql',
 'escalations',
 'notifications',
 'ms',
 'sql',
 'reporting',
 'services',
 'sap',
 'convergent',
 'charging',
 'cc',
 'big',
 'data',
 'software',
 'architecture',
 'cp3',
 'migration',
 'documentation',
 'mfd',
 'hyperion',
 'web',
 'analysis',
 'reporting',
 'nortel',
 'data',
 'center',
 'transformation',
 'dct',
 'oracle',
 'ebs',
 'standard',
 'benefits',
 'adobe',
 'photoshop',
 'sap',
 'real',
 'estate',
 'opentext',
 'software',
 'licensing',
 'content',
 'delivery',
 'network',
 'cdn',
 'microstrategy',
 'cert',
 'spclst',
 'admin',
 'mcsad',
 'siebel',
 'email',
 'response',
 'siebel',
 'os',
 'hpux',
 'mckesson',
 'emergency',
 'department',
 'infosystem',
 'opentext',
 'appworks',
 'onesource',
 'state',
 'compliance',
 'job',
 'control',
 'language',
 'jcl',
 'cerner',
 'population',
 'health',
 'metasaas',
 'ibm',
 'tririga',
 'real',
 'estate',
 'management',
 'adobe',
 'lightroom',
 'servicenow',
 'update',
 'sets',
 'restsharp',
 'sap',
 'ariba',
 'slp',
 'jde',
 'business',
 'services',
 'datawarehouse',
 'cloud',
 'dwc',
 'configurator',
 'cloud',
 'cloud',
 'data',
 'modeling',
 'oracle',
 'ebs',
 'infra',
 'exalogic',
 'postgis',
 'oracle',
 'ebs',
 'bi',
 'publisher',
 'microsoft',
 'focus',
 'cobol',
 'qualiac',
 'outils',
 'architect',
 'quantum',
 'photonics',
 'netsuite',
 'ge',
 'healthcare',
 'centricity',
 'edi',
 'annotated',
 'xml',
 'axml',
 'oracle',
 'taleo',
 'performance',
 'management',
 'custom',
 'metrics',
 'scorecards',
 'epiccare',
 'inpatient',
 'orders',
 'aws',
 'ar',
 'vr',
 'iot',
 'thingworx',
 'microsoft',
 'biztalk',
 'fundamentals',
 'benefits',
 'sap',
 'ewm',
 'inbound',
 'process',
 'ip',
 'ewm',
 'ehs',
 'integration',
 'sap',
 'fi',
 'actual',
 'costing',
 'mat',
 'ledger',
 'microsoft',
 'focus',
 'cobol',
 'oracle',
 'cloud',
 'projects',
 'mgt',
 'sap',
 'integration',
 'sap',
 'process',
 'integration',
 'pi',
 'industry',
 '40',
 'sap',
 'crm',
 'c4c',
 'cloud',
 'application',
 'studio',
 'forcecom',
 'oracle',
 'hcm',
 'cloud',
 'succession',
 'planning',
 'drug',
 'safety',
 'systems',
 'configuration',
 'orchestrationautomation',
 'design',
 'impl',
 'fccm',
 'enterprise',
 'case',
 'management',
 'ascend',
 'meditech',
 'laboratory',
 'microbiology',
 'adversarial',
 'simulation',
 'hp',
 'aioxpmsa',
 'ibm',
 'guardium',
 'sap',
 'bex',
 'web',
 'application',
 'designer',
 'activemq',
 'code',
 'deploy',
 'pen',
 'tek',
 'penzip',
 'designing',
 'performance',
 'testing',
 'oracle',
 'application',
 'express',
 'oracle',
 'grc',
 'administrator',
 'hyperion',
 'financial',
 'reporting',
 'scss',
 'oracle',
 'hcm',
 'cloud',
 'social',
 'network',
 'sap',
 'software',
 'compliance',
 'audit',
 'cerner',
 'bridge',
 'cerner',
 'cerner',
 'medical',
 'necessity',
 'process',
 'automation',
 'workflow',
 'sap',
 'extended',
 'warehouse',
 'mgmt',
 'ewm',
 'peoplesoft',
 'planning',
 'budgeting',
 'microsoft',
 'azure',
 'networking',
 'oculus',
 'quill',
 'jde',
 'apparel',
 'management',
 'ge',
 'centricity',
 'clinical',
 'archive',
 'adaptable',
 'database',
 'system',
 'adabas',
 'oracle',
 'ebs',
 'payroll',
 'sap',
 'ibp',
 'demand',
 'sensing',
 'dealroom',
 'netsuite',
 'warranty',
 'repairs',
 'management',
 'online',
 'transaction',
 'processing',
 'guidewire',
 'billing',
 'center',
 'cerner',
 'clinical',
 'reporting',
 'ibm',
 'watson',
 'analytics',
 'software',
 'ag',
 'webmethods',
 'activetransfer',
 'sap',
 'apo',
 'master',
 'data',
 'md',
 'quest',
 'software',
 'archive',
 'manager',
 'advanced',
 'persistent',
 'threats',
 'iworks',
 'prophet',
 'glean',
 'allscripts',
 'hospital',
 'systems',
 'sunrise',
 'oracle',
 'cloud',
 'conversion',
 'webservices',
 'crm',
 'ivr',
 'speech',
 'recognition',
 '5g',
 'opticalfiber',
 'network',
 'planning',
 'sap',
 'successfactors',
 'rewards',
 'recog',
 'rnr',
 'apache',
 'tomcat',
 'servlet',
 'container',
 'sap',
 'isu',
 'device',
 'management',
 'epic',
 'mychart',
 'patient',
 'portal',
 'access',
 'mail',
 'servers',
 'design',
 'implementation',
 'amazon',
 'lambda',
 'sap',
 'fico',
 'project',
 'accounting',
 'opentext',
 'software',
 'compliance',
 'audit',
 'microsoft',
 'azure',
 'ad',
 'hybrid',
 'identity',
 'icsot',
 'sensing',
 'logging',
 'architecture',
 'orchestrat',
 'tech',
 'sap',
 'mm',
 'vendor',
 'edi',
 'ibm',
 'security',
 'access',
 'manager',
 'isam',
 'epic',
 'cadence',
 'scheduling',
 'software',
 'governance',
 'software',
 'governance',
 'basware',
 'oracle',
 'erp',
 'cloud',
 'projects',
 'cutover',
 'management',
 'moq',
 'sap',
 'personnel',
 'administration',
 'sap',
 'hr',
 'performance',
 'management',
 'pm',
 'check',
 'pointgaia',
 'order',
 'management',
 'epic',
 'bridges',
 'interface',
 'email',
 'security',
 'ms',
 'azure',
 'backup',
 'intelligent',
 'asset',
 'management',
 'iam',
 'microsoft',
 'net',
 'windows',
 'forms',
 'ca',
 'cloudminder',
 'ftp',
 'sap',
 'fi',
 'general',
 'ledger',
 'ibm',
 'tivoli',
 'workload',
 'scheduler',
 'tws',
 'inf',
 'entreprise',
 'data',
 'integration',
 'edi',
 'jde',
 'project',
 'management',
 'azure',
 'synapse',
 'analytics',
 'aspera',
 'smarttrack',
 'operations',
 'ddmrp',
 'ibp',
 'data',
 'center',
 'racking',
 'technology',
 'solution',
 'architecture',
 'assurance',
 'sap',
 'hr',
 'organizational',
 'management',
 'om',
 'oracle',
 'ebs',
 'flow',
 'manufacturing',
 'sap',
 'engineering',
 'control',
 'center',
 'ectr',
 's4',
 'hana',
 'sap',
 'innovation',
 'management',
 'eac',
 'meditech',
 'anatomical',
 'pathology',
 'sap',
 'business',
 'information',
 'warehouse',
 'oracle',
 'ebs',
 'access',
 'control',
 'oracle',
 'cloud',
 'extension',
 'jcs',
 'sx',
 'siebel',
 'audit',
 'trail',
 'clm',
 'tools',
 'expertise',
 'eg',
 'sirionlabs',
 'etc',
 'sap',
 'mro',
 'procurement',
 'postgis',
 'amazon',
 'iot',
 'platform',
 'property',
 'tax',
 'management',
 'system',
 'ptms',
 'sap',
 'fico',
 'product',
 'cost',
 'controlling',
 'pc',
 'cerner',
 'acute',
 'care',
 'powerchart',
 'ftp',
 'oracle',
 'ebs',
 'interfaces',
 'bitbucket',
 'adobe',
 'digital',
 'publishing',
 'suite',
 'jde',
 'advanced',
 'stock',
 'valuation',
 'autotester',
 'cisco',
 'unified',
 'communications',
 'mgr',
 'cucm',
 'oracle',
 'system',
 'testing',
 'ms',
 'power',
 'bi',
 'report',
 'server',
 'sap',
 'performance',
 'testing',
 'ms',
 'bot',
 'framework',
 'sap',
 'mm',
 'vendor',
 'edi',
 'sap',
 'lumira',
 'crowdstrike',
 'informatica',
 'axon',
 'sap',
 'mdg',
 'brf',
 'integration',
 'simple',
 'reports',
 'oracle',
 'webcenter',
 'siteswcs',
 'semantic',
 'tooling',
 'oracle',
 'big',
 'data',
 'golden',
 'gate',
 'axway',
 'managed',
 'file',
 'transfer',
 'nuvolo',
 'maintenance',
 'management',
 'economic',
 'scenario',
 'generators',
 'appscan',
 'source',
 'capability',
 'maturity',
 'model',
 'int',
 'cmmi',
 'ibm',
 'zlinux',
 'mainframe',
 'financial',
 'information',
 'model',
 'qliksense',
 'administration',
 'microsoft',
 'azure',
 'data',
 'lake',
 'store',
 'lonworks',
 'protocol',
 'security',
 'salesforcecom',
 'consoles',
 'canvas',
 'ms',
 'azure',
 'hdinsight',
 'google',
 'search',
 'appliance',
 'netflow',
 'salesforce',
 'vlocity',
 'petapoco',
 'agile',
 'design',
 'delivery',
 'nuix',
 'ms',
 'visual',
 'studio',
 'ca',
 'unicenter',
 'netsuite',
 'upsell',
 'manager',
 'sap',
 'pp',
 'production',
 'planning',
 'process',
 'murex',
 'cent',
 'bnksagncies',
 'conf',
 'deploy',
 'bvd',
 'amadeus',
 'citrix',
 'administrator',
 'xenapp',
 '6',
 'sap',
 'flexible',
 'real',
 'estate',
 'mgmt',
 'refx',
 'netsuite',
 'suite',
 'analytics',
 'smart',
 'cities',
 'sap',
 'businessobjects',
 'analysis',
 'office',
 'seibel',
 'enterprise',
 'app',
 'architecture',
 'live',
 'meeting',
 'idaas',
 'dec',
 'knowledge',
 'management',
 'systems',
 'siebel',
 'query',
 'administration',
 '80211',
 'security',
 'sap',
 'data',
 'services',
 'oracle',
 'directory',
 'services',
 'epic',
 'beaker',
 'labs',
 'clinical',
 'pathology',
 'backup',
 'design',
 'implementation',
 'netsuite',
 'employee',
 'expenses',
 'public',
 'private',
 'hybrid',
 'cloud',
 'quantum',
 'strawberry',
 'fields',
 'osi',
 'murex',
 'collat',
 'mgmt',
 'config',
 'deploy',
 'siebel',
 'eautomotive',
 'calypso',
 'central',
 'banking',
 'reqs',
 'design',
 'backend',
 'development',
 'services',
 'cloudera',
 'backup',
 'disast',
 'recov',
 'bdr',
 'pitchbook',
 'axway',
 'api',
 'management',
 'design',
 'solution',
 'infrastructure',
 'oracle',
 'hyperion',
 'fdm',
 'count',
 'lines',
 'code',
 'cloc',
 'mainframe',
 'management',
 'linux',
 'kalilinux',
 'meditech',
 'electronic',
 'health',
 'record',
 'data',
 'archiving',
 'qlik',
 'software',
 'compliance',
 'audit',
 'netsuite',
 'upsell',
 'manager',
 'production',
 'scheduling',
 'oracle',
 'fixed',
 'assets',
 'sap',
 'security',
 'bibw',
 'apache',
 'hadoop',
 'hana',
 'integration',
 'mainframe',
 'hardware',
 'jde',
 'quality',
 'management',
 'oracle',
 'cloud',
 'ics',
 'sap',
 'runbook',
 'one',
 'smart',
 'close',
 'epicenter',
 'sap',
 'analytics',
 'cloud',
 'neotys',
 'sitecore',
 'experience',
 'commerce',
 'sap',
 'customer',
 'sd',
 'sales',
 'sls',
 'mcafee',
 'vulnerability',
 'manager',
 'foundstone',
 'salesforcecom',
 'architecture',
 'oracle',
 'setup',
 'automation',
 'peoplesoft',
 'human',
 'resources',
 'hr',
 'magento',
 'primavera',
 'p6',
 'google',
 'search',
 'appliance',
 'finance',
 'data',
 'conversion',
 'iload',
 'peoplesoft',
 'time',
 'labor',
 'majesco',
 'ba',
 'netscape',
 'annotated',
 'xml',
 'axml',
 'informatica',
 'cloud',
 'data',
 'management',
 'business',
 'finance',
 'analytics',
 'sap',
 'bpc',
 'corporate',
 'perf',
 'measurement',
 'cpm',
 'avaloq',
 'adobe',
 'experience',
 'manager',
 'communities',
 'double',
 'click',
 'pix',
 'firewall',
 'sap',
 'tm',
 'freight',
 'forwarder',
 'jde',
 'modules',
 'functional',
 'testing',
 'hp',
 'cloud',
 'computing',
 'hyperion',
 'strategic',
 'fin',
 'performance',
 'mgmt',
 'peoplesoft',
 'cs',
 'student',
 'records',
 'prehire',
 'tracking',
 'convergys',
 'android',
 'studio',
 'allegro',
 'na',
 'sniffer',
 'peoplesoft',
 'grants',
 'meditech',
 'anatomical',
 'pathology',
 'apache',
 'ranger',
 ...]

In [21]:
af['lable']=None

In [22]:
for i in range(34116):
  for j in af['stop_free1'][i]:
    for k in skills:
      if j==k:
        af['lable'][i]="technical"

In [ ]:
af

,RAW DATA,clean_data,lower_text1,tokenize1,stop_free1,lable
0,What ifs,What ifs,what ifs,"[what, ifs]",[ifs],None
1,seniority,seniority,seniority,[seniority],[seniority],None
2,familiarity,familiarity,familiarity,[familiarity],[familiarity],None
3,functionalities,functionalities,functionalities,[functionalities],[functionalities],None
4,Lambdas,Lambdas,lambdas,[lambdas],[lambdas],None
...,...,...,...,...,...,...
34111,negotiation,negotiation,negotiation,[negotiation],[negotiation],None
34112,deadlines,deadlines,deadlines,[deadlines],[deadlines],None
34113,"Self-motivated, enthusiastic and strong drive",Selfmotivated enthusiastic and strong drive,selfmotivated enthusiastic and strong drive,"[selfmotivated, enthusiastic, and, strong, drive]","[selfmotivated, enthusiastic, strong, drive]",None
34114,negotiation,negotiation,negotiation,[negotiation],[negotiation],None
34115,deadlines,deadlines,deadlines,[deadlines],[deadlines],None

Warning: total number of rows (34116) exceeds max_rows (20000). Limiting to first (20000) rows.

In [23]:
for i in range(34116):
  if af['lable'][i]==None:
    af['lable'][i]='Non technical'

In [24]:
af

,RAW DATA,clean_data,lower_text1,tokenize1,stop_free1,lable
0,What ifs,What ifs,what ifs,"[what, ifs]",[ifs],Non technical
1,seniority,seniority,seniority,[seniority],[seniority],Non technical
2,familiarity,familiarity,familiarity,[familiarity],[familiarity],Non technical
3,functionalities,functionalities,functionalities,[functionalities],[functionalities],Non technical
4,Lambdas,Lambdas,lambdas,[lambdas],[lambdas],Non technical
...,...,...,...,...,...,...
34111,negotiation,negotiation,negotiation,[negotiation],[negotiation],Non technical
34112,deadlines,deadlines,deadlines,[deadlines],[deadlines],Non technical
34113,"Self-motivated, enthusiastic and strong drive",Selfmotivated enthusiastic and strong drive,selfmotivated enthusiastic and strong drive,"[selfmotivated, enthusiastic, and, strong, drive]","[selfmotivated, enthusiastic, strong, drive]",Non technical
34114,negotiation,negotiation,negotiation,[negotiation],[negotiation],Non technical
34115,deadlines,deadlines,deadlines,[deadlines],[deadlines],Non technical

Warning: total number of rows (34116) exceeds max_rows (20000). Limiting to first (20000) rows.

In [25]:
af1 = pd.read_csv("/content/Raw_Skills_Dataset.csv")

In [26]:
af1['lables']=None

In [27]:
for i in range(34116):
  af1['lables'][i]=af['lable'][i]

In [28]:
af1

                                            RAW DATA         lables
0                                           What ifs  Non technical
1                                          seniority  Non technical
2                                        familiarity  Non technical
3                                    functionalities  Non technical
4                                            Lambdas  Non technical
...                                              ...            ...
34111                                    negotiation  Non technical
34112                                      deadlines  Non technical
34113  Self-motivated, enthusiastic and strong drive  Non technical
34114                                    negotiation  Non technical
34115                                      deadlines  Non technical

[34116 rows x 2 columns]

In [29]:
af1.to_csv('raw_lables.csv',index=False)

In [30]:
! ls

Example_Technical_Skills.csv  Raw_Skills_Dataset.csv
raw_lables.csv		      sample_data